### PR TITLE
Fix reversed Iron Chest textures

### PR DESCRIPTION
**Pull request by CivilNikolas**
Fixed broken iron chest textures

### CODE REVIEW

**Comment by ChloeDawn** [comment]
Looks good! But can you provide a screenshot to show the fix applied?

**Comment by CivilNikolas** [comment]
There you go. I think now they are correct. 
before
after

**Review by ChloeDawn — APPROVED** [review]

**Comment by CyanideX** [comment]
Those were not correct, btw, @ChloeDawn. 😝

**Comment by CyanideX** [comment]
image
 See back hinges on top front and bottom.

**Comment by ChloeDawn** [comment]
Oh no

**Comment by CivilNikolas** [comment]
I noticed too. I think I fixed them now. They were upside down and back to front. I'll put up the new ones again and you can merge them if you want.

**Pull request merged**
